services:
  db:
    image: mariadb:10.9
    environment:
      MARIADB_ROOT_PASSWORD: password

    volumes:
      - ./dbdata:/var/lib/mysql:rw
      - ./run:/run
    ports:
      - 3306:3306

  monstermac:
    image: flickpp/monstermac:0.1
    volumes:
      - ./secrets:/run/secrets:ro
    environment:
      MONSTERMAC_MODE: MODE16
    ports:
      - ${PLANTPOT_MONSTER_MAC_PORT}:8081

  rabbitmq:
    image: rabbitmq:3.11
    ports:
      - ${PLANTPOT_RABBITMQ_PORT}:5672

  websocket:
    image: flickpp/websocket:0.1
    ports:
      - ${PLANTPOT_WEBSOCKET_WEBSOCKET_PORT}:8080
      - ${PLANTPOT_WEBSOCKET_MSG_PORT}:8081

  kvstore:
    build:
      context: .
      args:
        SERVICE_NAME: kvstore
        KVSALT_PATH: secrets/tempkvsalt

    ports:
      - ${PLANTPOT_KV_STORE_PORT}:8080
    depends_on:
      - db
    environment:
      CASKET_RETURN_STACKTRACE_IN_BODY: 1

  oauth:
    build:
      context: .
      args:
        SERVICE_NAME: oauth
        KVSALT_PATH: secrets/oauth_kvsalt

    ports:
      - ${PLANTPOT_OAUTH_PORT}:8080
    depends_on:
      - kvstore
      - monstermac
    volumes:
      - ./secrets:/run/secrets:ro
    environment:
      CASKET_RETURN_STACKTRACE_IN_BODY: 1

  images:
    build:
      context: .
      args:
        SERVICE_NAME: images
        KVSALT_PATH: secrets/tempkvsalt
      volumes:
        - ./blobs:/blobs:rw
      environment:
        CASKET_RETURN_STACKTRACE_IN_BODY: 1

    ports:
      - ${PLANTPOT_OAUTH_PORT}:8080
    depends_on:
      - kvstore
      - monstermac
    volumes:
      - ./secrets:/run/secrets:ro
    environment:
      CASKET_RETURN_STACKTRACE_IN_BODY: 1

  tuliptheclown:
    build:
      context: .
      args:
        SERVICE_NAME: tuliptheclown
        KVSALT_PATH: secrets/tuliptheclown_kvsalt

    volumes:
      - ./secrets:/run/secrets:ro
    environment:
      PLANTPOT_TULIPTHECLOWN_MESSAGE_TIMEOUT: 120
      CASKET_RETURN_STACKTRACE_IN_BODY: 1

    ports:
      - 40000:8080
    depends_on:
      - db
      - kvstore
      - oauth
      - websocket
