services:
  db:
    image: mariadb:10.9
    environment:
      MARIADB_ROOT_PASSWORD: password

    volumes:
      - ./dbdata:/var/lib/mysql:rw
      - ./run:/run
    ports:
      - 3306:3306

  monstermac:
    image: flickpp/monstermac:0.1
    volumes:
      - ./secrets:/run/secrets:ro
    environment:
      MONSTERMAC_MODE: MODE16
    ports:
      - ${PLANTPOT_MONSTERMAC_PORT}:8081

  rabbitmq:
    image: rabbitmq:3.11
    ports:
      - ${PLANTPOT_RABBITMQ_PORT}:5672

  rabbit-tail:
    build:
      context: .
      dockerfile: Dockerfile-rabbit
    volumes:
      - ./secrets:/run/secrets:ro
    depends_on:
      - rabbitmq
      - websocket

  websocket:
    image: flickpp/websocket:0.1
    ports:
      - ${PLANTPOT_WEBSOCKET_WEBSOCKET_PORT}:8080
      - ${PLANTPOT_WEBSOCKET_MSG_PORT}:8081

  kvstore:
    build:
      context: .
      args:
        SERVICE_NAME: kvstore
    ports:
      - ${PLANTPOT_KVSTORE_PORT}:8080
    depends_on:
      - db
    environment:
      CASKET_RETURN_STACKTRACE_IN_BODY: 1

  user:
    build:
      context: .
      args:
        SERVICE_NAME: user
    ports:
      - ${PLANTPOT_USER_PORT}:8080
    environment:
      CASKET_RETURN_STACKTRACE_IN_BODY: 1

  oauth:
    build:
      context: .
      args:
        SERVICE_NAME: oauth
    ports:
      - ${PLANTPOT_OAUTH_PORT}:8080
    depends_on:
      - monstermac
      - kvstore
    volumes:
      - ./secrets:/run/secrets:ro
    environment:
      CASKET_RETURN_STACKTRACE_IN_BODY: 1

  blobs:
    build:
      context: .
      args:
        SERVICE_NAME: blobs
    ports:
      - ${PLANTPOT_BLOBS_PORT}:8080
    volumes:
      - ./blobs:/blobs:rw
    environment:
      CASKET_RETURN_STACKTRACE_IN_BODY: 1
      PLANTPOT_BLOBS_DIR: /blobs
    depends_on:
      - monstermac

  tuliptheclown:
    build:
      context: .
      dockerfile: services/tuliptheclown/Dockerfile

    volumes:
      - ./secrets:/run/secrets:ro
    environment:
      PLANTPOT_TULIPTHECLOWN_MESSAGE_TIMEOUT: 120
      CASKET_RETURN_STACKTRACE_IN_BODY: 1

    ports:
      - 40000:8080
    depends_on:
      - db
      - kvstore
      - oauth
      - rabbitmq
